config/routes.rb
Postit::Application.routes.draw do
  root to: 'posts#index'

  resources :posts, except: [:destroy] do
    member do
      post 'vote'
    end
    collection do
      post 'archive'
    end
    resources :comments, only: [:create]
      member do
        post 'vote'
      end
  end

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create, :destroy]

  resources :categories

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  get '/register', to: 'users#new'
  post '/register', to: 'users#create'

  get '/logout', to: 'sessions#destroy'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :post_categories
  has_many :posts, through: :post_categories
end  

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  has_many :votes, as: :voteable

  validates :text, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories
  has_many :votes, as: :voteable

  validates :title, presence: true
  validates :artist, presence: true
  validates :url, presence: true

  def vote_total
    self.votes.where(vote: true).size - self.votes.where(vote: false).size
  end
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  has_many :posts
  has_many :comments
  has_many :votes
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :voteable, polymorphic: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:error] = "Wait a sec, you need to log in first!"
      redirect_to root_path
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end
    
  def show
    @category = Category.find(params[:id])
  end

  def new
  end

  def create
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_filter :require_user, only: [:new, :create]

  def create 
    @post = Post.find(params[:post_id])
    @comment = Comment.new(params[:comment])
    @comment.user_id = @current_user.id # TODO set to logged in user
    @comment.post = @post

    if @comment.save
      redirect_to post_path(@comment.post)
    else
      render 'posts/show'
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :require_user, only: [:new, :create, :vote]
  before_filter :find_post, only: [:edit, :update, :vote] #creates the @post variable for the require_creator filter.
  before_filter :require_creator, only: [:edit, :update]

  def index
    @posts = Post.all
  end
    
  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create 
    @post = Post.new(params[:post])
    @post.user_id = @current_user.id
   
    if @post.save
      #flash[:notice] = "Post was created"
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post.update_attributes(params[:post])
    redirect_to root_path
  end

  def vote
    Vote.create(voteable: @post, user: current_user, vote: params[:vote])

    respond_to do |format|
      format.html do
        #flash[:notice]
        redirect_to :back
      end
      format.js
    end
  end


# Filter Methods
  
  def find_post
    @post = Post.find(params[:id])
  end

  def require_creator
    unless logged_in? && current_user == @post.user
      flash[:error] = "You're not allowed to do that."
      redirect_to root_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.where(username: params[:username]).first

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      #flash[:notice] = "Howdy, you're now logged in."
      redirect_to root_path

    else
      flash[:error] = "Your username and password aren't on the guestlist. Try again or register."
      redirect_to new_user_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Thank you. Come again."
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create 
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome aboard!"
      redirect_to root_path
    else
      render 'posts/show'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/show.html.erb
<table class="table table-striped table-bordered">
  <% @category.posts.reverse.each do |p| %>
  <tr>
    <td><%= link_to "#{p.artist} - #{p.title}", p.url, target: '_blank' %> 
    </td>
    <td><%= time_ago_in_words(p.created_at) %> ago
    </td>
    <td><%= p.user.username %>
    </td>
    <td>
        <% p.categories.each do |c| %>
        <span class="label"><%= c.name %></span>
        <% end %>
    </td>
    <td>
        <% if p.comments.count > 0 %>
          <%= link_to pluralize(p.comments.count, "comment"), post_path(p.id) %> 
        <% else %>
          <%= link_to "No Comments", post_path(p.id) %>
        <% end %>
    </td>
  </td>
  <% end %>
 </tr>
</table>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= [:notice, :success].include?(name) ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav pull-left">
    <li>
      <%= link_to "BeatMountain", root_path, :class => 'brand' %>
    </li>
    <li>
      <%= link_to 'Submit', new_post_path %>
    </li>
    <div class="btn-group">
      <a href="#" class="btn dropdown-toggle" data-toggle="dropdown">
      Category
      <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
          <% Category.all.each do |c| %>
            <li><%= link_to c.name, c %></li>
          <% end %>
    </ul>
  </ul>
  <ul class="nav pull-right">
    <% if current_user %>
      <li>
          <p class="navbar-text"><%= current_user.username %></p>
      </li>
      <li>
        <%= link_to 'Logout', logout_path %>
      </li>
    <% else %>
      <li>
        <%= link_to 'Register', register_path %>
      </li>
      <li>
        <%= link_to 'Login', login_path %>
      </li>
    <% end %>
  </ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BeatMountain</title>
    <meta name="description" content="">
    <meta name="author" content="@glenn0">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="container"> 
        <div class="row">
          <div class="span12">
            <div class="navbar">
              <div class="navbar-inner navtweaks">
                <%= render 'layouts/navigation' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer> 
          <div><p style="text-align:right; color:lightgrey">Made by <a href="http://twitter.com/glenn0">Glenn</a> at <a href="http://gotealeaf.com/">Tealeaf Academy</a>.</p></div>   
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/edit.html.erb
<h5>Tweak a beat...<h5>

<% if @post.errors.any? %>
  <div class="alert alert-error">
    <%= @post.errors.full_messages.join(', ') %>
  </div>
<% end %>

<%= form_for @post do |f| %>

  <%= f.label :url, 'Link' %>
  <%= f.text_field :url %>
  <br/>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br/>
  <%= f.label :artist %>
  <%= f.text_field :artist %>
  <br/>
  <%= f.label :category_ids, "Category" %>
  <%= f.select :category_ids, Category.all.collect{|c| [c.name, c.id]}, {}, {multiple: 'multiple'} %>
  <br/>
  <%= f.label :description, "What's so good about it?" %>
  <%= f.text_field :description %>
  <br/>
  <%= f.submit "Submit", :class => "btn" %>
<% end %>

app/views/posts/index.html.erb
<table class="table table-striped table-bordered">
  <% @posts.reverse.each do |p| %>
  <tr>
    <td>
      <%= link_to vote_post_path(p, vote: false), method: 'post', 'data-remote' => true do %>
        -
      <% end %>

      <span class="label" id="posts_vote_<%= p.id %>"><%= p.vote_total %></span>

      <%= link_to vote_post_path(p, vote: true), method: 'post', 'data-remote' => true do %>
        +
      <% end %>
    </td>    
    <td><%= link_to "#{p.artist} - #{p.title}", p.url, target: '_blank' %> 
    </td>
    <td><%= time_ago_in_words(p.created_at) %> ago
    </td>
    <td><%= p.user.username %>
    </td>
    <td>
        <% p.categories.each do |c| %>
        <span class="label"><%= c.name %></span>
        <% end %>
    </td>
    <td>
        <% if p.comments.count > 0 %>
          <%= link_to pluralize(p.comments.count, "comment"), post_path(p.id) %> 
        <% else %>
          <%= link_to "No Comments", post_path(p.id) %>
        <% end %>
    </td>
  <% end %>
 </tr>
</table>

app/views/posts/new.html.erb
<h5>Drop a beat...<h5>

<% if @post.errors.any? %>
  <div class="alert alert-error">
    <%= @post.errors.full_messages.join(', ') %>
  </div>
<% end %>

<%= form_for @post do |f| %>

  <%= f.label :url, 'Link' %>
  <%= f.text_field :url %>
  <br/>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br/>
  <%= f.label :artist %>
  <%= f.text_field :artist %>
  <br/>
  <%= f.label :category_ids, "Category" %>
  <%= f.select :category_ids, Category.all.collect{|c| [c.name, c.id]}, {}, {multiple: 'multiple'} %>
  <br/>
  <%= f.label :description, "What's so good about it?" %>
  <%= f.text_field :description %>
  <br/>
  <%= f.submit "Submit", :class => "btn" %>
<% end %>

app/views/posts/show.html.erb
<table class="table table-striped table-bordered">
  <tr>
    <td>Artist</td>
    <td><%= @post.artist %></td>
  </tr>
  <tr>
    <td>Title</td>
    <td><%= @post.title %></td>
  </tr>
  <tr>
    <td>Link</td>
    <td><a href="<%= @post.url %>" target="_blank"><%= @post.url %></td>
  </tr>
  <tr>
    <td>Dropped by</td>
    <td><%= @post.user.username %>
  </tr>
  <tr>
    <td>Dropped at</td>
    <td><%= @post.created_at %>
  </tr>
  <tr>
    <td>Why?</td>
    <td><%= @post.description %></td>
  </tr>
</table>

<% if logged_in? && current_user == @post.user %>
  <%= link_to "Edit", edit_post_path(@post), class: 'btn btn-mini pull-right' %>
<% end %>

<br/>

<% if @comment.errors.any? %>
  <div class="alert alert-error">
    <%= @comment.errors.full_messages.join(', ') %>
  </div>
<% end %> 

<%= form_for [@post, @comment] do |f| %>
  <%= f.text_area :text, rows: 2 %>
  <br/>
  <%= f.submit "Add Comment", :class => "btn"  %>
<% end %>

<table class="table table-striped table-bordered"> 
  <% @post.comments.reverse.each do |c| %>
    <tr>
      <td><%= c.text %></td>
      <td><%= c.user.username %></td>
      <td><%= time_ago_in_words(c.created_at) %> ago</td>
    </td>
  <% end %>
</table>

app/views/posts/vote.js.erb
//alert("You submitted a vote for <%= @post.id %>. It's now at <%= @post.vote_total %>!");

$("#posts_vote_<%= @post.id %>").html("<%= @post.vote_total %>")

app/views/users/new.html.erb
<h3>Register</h3>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <br/>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br/>
  <%= f.submit "Register", :class => "btn" %>
<% end %>